### ISSUE TITLE
请教下，WebRTC-Server与mediasoup janus 等网关的区别？

### ISSUE THREAD

**Issue by devfreq074** [KingsleyYau/WebRTC-Server#5]
您好，请教下，WebRTC-Server与mediasoup janus 等网关有哪些区别呢？

**Comment by KingsleyYau** [comment]
> 您好，请教下，WebRTC-Server与mediasoup janus 等网关有哪些区别呢？

janus等是基于两端都是走rtc交换，媒体流是rtp的，WebRTC-Server是接收rtc的上传，然后根据脚本分发为其他格式，如rtmp

**Comment by wusopp** [comment]
> > 您好，请教下，WebRTC-Server与mediasoup janus 等网关有哪些区别呢？
> 
> janus等是基于两端都是走rtc交换，媒体流是rtp的，WebRTC-Server是接收rtc的上传，然后根据脚本分发为其他格式，如rtmp

谢谢解答
